### ISSUE TITLE
gtop doesn't work on ubuntu 17.04 with cpu.js:8 error

### ISSUE THREAD

**Issue by Bashar** [aksakalli/gtop#47]
#### Environment

- OS: ubuntu 17.04 64bit
- Node version: v0.10.21
- gtop version: 0.1.5

#### Description

$ LANG=en_US.utf8 TERM=xterm-256color gtop

/usr/local/lib/node_modules/gtop/lib/monitor/cpu.js:8
  si.currentLoad(data => {
                       ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gtop/lib/monitor/index.js:2:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by aksakalli** [comment]
hi @Bashar, 

**gtop** requires Node.js >= v4. Please update your version (see [Installing Node.js via package manager](https://nodejs.org/en/download/package-manager/)).
